site_name: IHC - Zupper

repo_url: https://github.com/Interacao-Humano-Computador/2020.1-Grupo06TA

theme: 
  name: material

nav:
  - Sobre o projeto: index.md
  - Mais informações:
    - Motivações: motivacao.md
    - Planejamento do projeto: 
      - Metodologia: metodologia.md
      - Cronograma: cronograma.md
    - Sites avaliados: 
      - INPE: inpe.md
      - Globo.com: globo.md
    - Ferramentas: ferramentas.md
    - Processo de design: processo-design.md
    - Politicas: politicas.md