site_name: IHC - Zupper

repo_url: https://github.com/Interacao-Humano-Computador/2020.1-Zupper

theme: 
  name: material

nav:
  - Sobre o projeto: index.md
  - Analise de tarefas: analise-tarefas.md
  - Ferramentas: ferramentas.md
  - Motivações: motivacao.md
  - Personas: 
    - Dyana Silva: dyana-silva.md
    - Ednaldo Pereira: ednaldo-pereira.md
    - Pedro Lucas: pedro-lucas.md
  - Planejamento do projeto: 
    - Cronograma: cronograma.md
    - Metodologia: metodologia.md
  - Políticas: politicas.md
  - Processo de design: processo-design.md
  - Princípios gerais do projeto: principios-gerais.md
  - Sites avaliados: 
    - INPE: inpe.md
    - Globo.com: globo.md